language: node_js
node_js:
  - "6"
install:
  - npm install
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE scribedb;'
  - mysql -e 'CREATE TABLE scribedb.Messages (
      id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
      text VARCHAR(255)
    );'
