language: node_js
node_js:
  - "6"
install:
  - npm install
services:
  - mysql
before_script:
  - mysql -e 'create database scribedb;'
  - mysql -e 'use scribedb'
  - mysql -e 'create table Messages (text VARCHAR(255))';
